#!/bin/bash
DESTDIR=${1:-}
SRCDIR=${2:-.}

mkdir -p ${DESTDIR}/sbin
cp ${SRCDIR}/sbin/restore_boot ${DESTDIR}/sbin/restore_boot
cp ${SRCDIR}/sbin/init_overlay ${DESTDIR}/sbin/init_overlay
cp ${SRCDIR}/sbin/init_overlay_second ${DESTDIR}/sbin/init_overlay_second
cp ${SRCDIR}/sbin/create_overlay ${DESTDIR}/sbin/create_overlay

mkdir -p ${DESTDIR}/etc/coderbot
cp ${SRCDIR}/etc/coderbot/init_overlay.conf ${DESTDIR}/etc/coderbot/init_overlay.conf

#mkdir -p ${DESTDIR}/bin
#cp ${SRCDIR}bin/tar_sig ${DESTDIR}bin/tar_sig

chmod +x ${DESTDIR}/sbin/restore_boot
chmod +x ${DESTDIR}/sbin/init_overlay
chmod +x ${DESTDIR}/sbin/init_overlay_second
chmod +x ${DESTDIR}/sbin/create_overlay
#chmod +x ${DESTDIR}bin/tar_sig

if grep "init=..*" /boot/cmdline.txt > /dev/null
then
    sed -i "s-init=[^ ]*-init=/sbin/init_overlay-" /boot/cmdline.txt
else
    sed -i 's-$- init=/sbin/init_overlay-' /boot/cmdline.txt
fi