#!/bin/bash

usage() {
	echo "backup_boot"
	echo "backup (tar.xz) boot to  /etc/coderbot/boot.tar.xz without signing"
	exit 2
}

fail(){
	echo $1
	exit 1
}

FORCE=${FORCE:-yes}
BOOTDIR=/boot

[[ $1 == "-h" || $1 == "--help" ]] && usage
BACKUPFILE=${BACKUPFILE:-/etc/coderbot/boot.tar.xz}
BACKUPSIG=${BACKUPSIG:-/etc/coderbot/boot.sig}

[ -d $BOOTDIR ] || fail "ERROR: BOOTDIR: $BOOTDIR not found"

if [ $FORCE = "yes" ]
then
    [ -f $BACKUPFILE ] && rm $BACKUPFILE || fail "ERROR: can't remove previous backup $BAKCUPFILE"
    [ -f $BACKUPSIG ] && rm $BACKUPSIG || fail "ERROR: can't remove previous backup sig $BAKCUPSIG"
fi

[-f $BACKUPFILE ] && fail "ERROR: file $BACKUPFILE already exists.\nDelete it (with signature), then retry."

tar cfvJ $BACKUPFILE -C $BOOTDIR . || fail "ERROR: can't backup BOOTDIR $BOOTDIR"