#!/bin/bash
# restore the boot partition from a backup and a signature
#
#

usage() {
	echo "restore_boot [BACKUPFILE] [DEVICE] [MOUNTPOINT] [LABEL]"
	echo "restore boot partition from a backup, verifying the signature if present"
	exit 2
}

MOUNTPOINT=${3:-/boot}
BACKUPFILE=${1:-/etc/coderbot/boot.tar.xz}
BACKUPSIG=${BACKUPSIG:-/etc/coderbot/boot.sig}
KEYRING=${KEYRING:-/etc/coderbot/coderbot.pub}
DEVICE=${2:-/dev/mmcblk0p1}
LABEL=${4:-BOOT}
FAT_SIZE=${FAT_SIZE:-32}

fail(){
	echo $1
	exit 1
}

verify(){
	[ -f $KEYRING ] || fail "ERROR: File not Found KEYRING: $KEYRING"
	gpg --no-default-keyring --keyring $KEYRING --verify $BACKUPSIG $BACKUPFILE || fail "ERROR: could not verify"
}

do_restore(){
	ls $DEVICE > /dev/null 2>&1 || fail "ERROR: Device not found $DEVICE"
	[ -d $MOUNTPOINT ] || fail "ERROR: Directory not found: MOUNTPOINT: $MOUNTPOINT"
	[ -f $BACKUPFILE ] || fail "ERROR: File not found BACKUPFILE: $BACKUPFILE"
	umount $DEVICE
	wipefs -a $DEVICE || fail "ERROR: could not wipefs"
	mkfs.vfat -F $FAT_SIZE -n $LABEL $DEVICE || fail "ERROR: could not mkfs"
	mount $DEVICE $MOUNTPOINT || fail "ERROR: could not mount"
	tar xfJ $BACKUPFILE -C $MOUNTPOINT --no-same-owner || fail "ERROR: could not restore backup"
}

[ -f $BACKUPFILE ] || fail "ERROR: $BACKUPFILE File not Found"
#[ -f $BACKUPSIG ] || fail "ERROR: $BACKUPSIG File not Found"
#[ -f $KEYRING ] || fail "ERROR: $KEYRING File not Found"

#verify only if signature is present
[ -f $BACKUPSIG ] && verify
do_restore
